Rebuild Permission System from main cloud as a module
CloudNet-v2/v2-permissionsystem pull request #1
Opened 2020-05-10 20:08 UTC by MeinerLP1

2020-05-10 21:13 UTC, GiantTreeLP requested changes

2020-05-10 21:13 UTC, GiantTreeLP commented on PermissionCore/src/main/java/eu/cloudnetsrvice/cloudpermission/model/CloudPlayer.java
> +    public static final Type TYPE = (new TypeToken<CloudPlayer>() {
Please use the TypeToken.get method here

2020-05-10 21:13 UTC, GiantTreeLP commented on PermissionCore/src/main/java/eu/cloudnetsrvice/cloudpermission/model/CloudPlayer.java
> +    }
Please recreate the equals method with IntelliJ

2020-05-10 21:13 UTC, GiantTreeLP commented on PermissionModule/src/main/java/eu/cloudnetservice/cloudpermission/module/config/ConfigPermissions.java
> +    private static final Type COLLECTION_PERMISSION_GROUP_TYPE = TypeToken.getParameterized(Collection.class, PermissionGroup.class)
We should move to concrete interfaces like List or Set in the future

2020-05-10 21:13 UTC, GiantTreeLP commented on PermissionPlugin/src/main/java/eu/cloudnetservice/cloudpermission/packet/out/PacketOutUpdatePlayer.java
> +        super(302, new Document("player", offlinePlayer));
I don't like this arbitrary number

2020-05-10 21:13 UTC, GiantTreeLP commented on PermissionPlugin/src/main/java/eu/cloudnetservice/cloudpermission/packet/out/PacketOutUpdatePermissionGroup.java
> +        super(201, new Document("permissionGroup", permissionGroup));
I don't like this arbitrary number

2020-05-10 21:13 UTC, GiantTreeLP commented on PermissionPlugin/src/main/java/eu/cloudnetservice/cloudpermission/listener/bungee/ProxiedPlayerListener.java
> +}
Please reformat this file

2020-05-10 21:34 UTC, MeinerLP1 commented on PermissionPlugin/src/main/java/eu/cloudnetservice/cloudpermission/packet/out/PacketOutUpdatePlayer.java
> +        super(302, new Document("player", offlinePlayer));
It only a copy from original code

2020-05-10 21:34 UTC, MeinerLP1 commented on PermissionPlugin/src/main/java/eu/cloudnetservice/cloudpermission/packet/out/PacketOutUpdatePermissionGroup.java
> +        super(201, new Document("permissionGroup", permissionGroup));
It only a copy from original code

2020-05-10 21:34 UTC, MeinerLP1 commented on PermissionPlugin/src/main/java/eu/cloudnetservice/cloudpermission/listener/bungee/ProxiedPlayerListener.java
> +}
I have already do it.

2020-05-11 08:18 UTC, GiantTreeLP approved these changes

2020-05-11 08:18 UTC, merged